import math
#variables (input/output/constant)
turbineRadius = 3 #radius of turbine blade in meter (input)
windSpeed=12.29 #average wind speed in meter per second (input)
turbineEfficiency =0.1 #the operating effeciency of the turbine, but converted to decimal for-
# convenience of calculation (input)
airDensity = 1.2 # the air density in kg/m^3 (constant)
highestWindSpeed=23.98*0.44704 #highest wind speed in MPH to meter per second
lowestWindSpeed = 8.25*0.44704 #lowest wind speed in MPH to meter per second

#calculation of surface area
squaredRadius = turbineRadius**2
surfaceArea = squaredRadius*(math.pi)

#calculation of Maximum power
maxPower = surfaceArea* (0.5)*(airDensity)*(highestWindSpeed**3) #implementing the calculation of Maximum power formula-
# (with air density, surface area of turbine, and wind speed) to get the maximum power can be generated by the turbine

#Calculatation of actual power of wind turbine
actualPower= maxPower*turbineEfficiency #compute the actual power generated by the turbine by-
# multiplying the maximum power generated by the trubine with the operating effeciency of the wind turbine in unit of W (J/s)

#calculation of number of turbine needed for one person in a year in oregon
numberOfTurbine= (2.57*10**10)/(actualPower*31556926)

#printing values to check if the values are accurate
print (numberOfTurbine)
print (maxPower)
print (actualPower) #final output of the program: the actual power of the wind turbine in W (J/s)
